---
version: '3.9'
services:
  node:
    image: svetekllc/massa:MAIN.2.1
    labels:
      network: mainnet
    env_file:
      - mainnet.env
    ports:
      - '31244:31244'
      - '31245:31245'
    volumes:
      - /opt/nvme3n1/massa:/app
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8gb
    networks:
      - massa
    restart: unless-stopped

networks:
  massa:
    name: massa