---
version: '3.9'
services:
  node-testnet:
    image: svetekllc/haqq:v1.6.1-node
    labels:
      network: testnet
    env_file:
      - testnet.env
    ports:
      - '20656:20656'
      - '20660:20660'
    volumes:
      - /opt/nvme0n1/haqq:/root/.haqqd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - haqq
    restart: unless-stopped

  node-mainnet:
    image: svetekllc/haqq:v1.6.3-node
    labels:
      network: mainnet
    env_file:
      - mainnet.env
    ports:
      - '10656:10656'
      - '10660:10660'
    volumes:
      - /opt/nvme1n1/haqq:/root/.haqqd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '16gb'
    networks:
      - haqq
    restart: unless-stopped

networks:
  haqq:
    name: haqq
