{
 "title": "Cadvisor exporter",
 "description": "Simple exporter for cadvisor only",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(cadvisor_version_info, job)"
    }
   },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(cadvisor_version_info{job=\"$job\"}, network)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(cadvisor_version_info{network=\"$network\"}, hostname)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\",  network=\"$network\",  container_label_network=~\"$network|\", hostname=\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{network=\"$network\",hostname=\"$host\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',network=\"$network\",hostname=\"$host\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{network=\"$network\",hostname=\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{network=\"$network\",hostname=\"$host\"}) /  count(count(node_cpu_seconds_total{network=\"$network\",hostname=\"$host\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{network=\"$network\",hostname=\"$host\"}) / count(count(node_cpu_seconds_total{network=\"$network\",hostname=\"$host\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{network=\"$network\",hostname=\"$host\"} * 100) / node_memory_MemTotal_bytes{network=\"$network\",hostname=\"$host\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{network=\"$network\",hostname=\"$host\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{network=\"$network\",hostname=\"$host\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{network=\"$network\",hostname=\"$host\"} - node_boot_time_seconds{network=\"$network\",hostname=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{network=\"$network\",hostname=\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{network=\"$network\",hostname=\"$host\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{network=\"$network\",hostname=\"$host\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{network=\"$network\", hostname=\"$host\", name=~\"$container\", name!=\"\", image!=\"\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name!=\"\", image!=\"\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name!=\"\", image!=\"\"}) by (name) / sum(container_spec_memory_limit_bytes{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name!=\"\", image!=\"\"}) by (name) * 100",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name!=\"\", image!=\"\"}) by (name) ",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name!=\"\", image!=\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name!=\"\", image!=\"\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name!=\"\"}[$__rate_interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{network=\"$network\", container_label_network=~\"$network|\", hostname=\"$host\", name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}