{
 "title": "Cardano Staking Monitoring",
 "description": "Stake Pool Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Summary Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cexplorer.io Rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapool_position{exported_instance=\"adapool\"}",
     "legendFormat": "AdaPools.org Rank"
    }
   ]
  },
  {
   "title": "Delegators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapool_delegators{exported_instance=\"adapool\"}",
     "legendFormat": "Delegators"
    }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "adapool_blocks_lifetime" }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{hostname=\"producer\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "bargauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{hostname=\"producer\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Live Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapool_stake{exported_instance=\"adapool\"}/1000000",
     "legendFormat": "Live Stake"
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "stat",
   "description": "in ADA",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapool_stake_active{exported_instance=\"adapool\"}/1000000",
     "legendFormat": "Active Stake"
    }
   ]
  },
  {
   "title": "Pledged (ADA)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "adapool_pledge{exported_instance=\"adapool\"}/1000000",
     "legendFormat": "ADA"
    }
   ]
  },
  {
   "title": "Remaining KES Periods",
   "type": "bargauge",
   "description": "Remaining KES periods before we need to rotate keys",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int{hostname=\"producer\"}",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Key rotation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "Current period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expiry period"
    },
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "Remaining"
    },
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "Days left"
    }
   ]
  },
  {
   "title": "Producer Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",hostname=\"producer\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=\"producer\"} / (node_memory_MemTotal_bytes{hostname=\"producer\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{hostname=\"producer\"} / node_memory_SwapTotal_bytes{hostname=\"producer\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/opt\",fstype!=\"rootfs\",hostname=\"producer\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/opt\",fstype!=\"rootfs\",hostname=\"producer\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected peers to/from Core Node",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_hot{hostname=\"producer\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Producer TX's processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{hostname=\"producer\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{hostname=\"producer\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{hostname=\"producer\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{hostname=\"producer\"} / (1000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay-RU Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",hostname=\"relay-ru\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=\"relay-ru\"} / (node_memory_MemTotal_bytes{hostname=\"relay-ru\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{hostname=\"relay-ru\"} / node_memory_SwapTotal_bytes{hostname=\"relay-ru\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/opt\",fstype!=\"rootfs\",hostname=\"relay-ru\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/opt\",fstype!=\"rootfs\",hostname=\"relay-ru\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_hot{hostname=\"relay-ru\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay TX's processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{hostname=\"relay-ru\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{hostname=\"relay-ru\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{hostname=\"relay-ru\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{hostname=\"relay-ru\"} / (1000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay-EU Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",hostname=\"relay-eu\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=\"relay-eu\"} / (node_memory_MemTotal_bytes{hostname=\"relay-eu\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{hostname=\"relay-eu\"} / node_memory_SwapTotal_bytes{hostname=\"relay-eu\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",hostname=\"relay-eu\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",hostname=\"relay-eu\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected peers to/from Relay 1",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_hot{hostname=\"relay-eu\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Relay TX's processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{hostname=\"relay-eu\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{hostname=\"relay-eu\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{hostname=\"relay-eu\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{hostname=\"relay-eu\"} / (1000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk (Relays)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System Load (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "node_load1{hostname=\"producer\"}*100",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{hostname=\"producer\"}*100",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{hostname=\"producer\"}*100",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "System Load (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "node_load1{hostname=\"relay-eu\"}*100",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{hostname=\"relay-eu\"}*100",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{hostname=\"relay-eu\"}*100",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "System Load (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "node_load1{hostname=\"relay-ru\"}*100",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{hostname=\"relay-ru\"}*100",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{hostname=\"relay-ru\"}*100",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "CPU Utilization (producer node)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"producer\",mode=\"system\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"producer\",mode=\"user\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"producer\",mode=\"iowait\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"producer\",mode=~\".*irq\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"producer\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"producer\",mode=\"idle\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "CPU Utilization (relay-eu node)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-eu\",mode=\"system\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-eu\",mode=\"user\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-eu\",mode=\"iowait\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-eu\",mode=~\".*irq\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-eu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-eu\",mode=\"idle\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "CPU Utilization (relay-ru node)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-ru\",mode=\"system\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-ru\",mode=\"user\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-ru\",mode=\"iowait\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-ru\",mode=~\".*irq\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-ru\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{hostname=\"relay-ru\",mode=\"idle\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Utilization (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=\"producer\"} / (node_memory_MemTotal_bytes{hostname=\"producer\"})))* 100",
       "legendFormat": "RAM Used"
      }
     ]
    },
    {
     "title": "Memory Utilization (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=\"relay-eu\"} / (node_memory_MemTotal_bytes{hostname=\"relay-eu\"})))* 100",
       "legendFormat": "RAM Used"
      }
     ]
    },
    {
     "title": "Memory Utilization (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{hostname=\"relay-ru\"} / (node_memory_MemTotal_bytes{hostname=\"relay-ru\"})))* 100",
       "legendFormat": "RAM Used"
      }
     ]
    },
    {
     "title": "Peak memory allocated (producer node)",
     "type": "graph",
     "description": "Counts only memory that is physically free (from OS, in MBytes)",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "rts_gc_peak_megabytes_allocated{hostname=\"producer\"}",
       "legendFormat": "RAM Used"
      }
     ]
    },
    {
     "title": "Peak memory allocated (relay-eu node)",
     "type": "timeseries",
     "description": "Counts only memory that is physically free (from OS, in MBytes)",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_peak_megabytes_allocated{hostname=\"relay-eu\"}",
       "legendFormat": "RAM Used"
      }
     ]
    },
    {
     "title": "Peak memory allocated (relay-ru node)",
     "type": "timeseries",
     "description": "Counts only memory that is physically free (from OS, in MBytes)",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_peak_megabytes_allocated{hostname=\"relay-ru\"}",
       "legendFormat": "RAM Used"
      }
     ]
    },
    {
     "title": "Network usage (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{hostname=\"producer\", device=~\"e[t,n][h,s][0-9]+\"}[1m])*8",
       "legendFormat": "{{device}} receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{hostname=\"producer\", device=~\"e[t,n][h,s][0-9]+\"}[1m])*8",
       "legendFormat": "{{device}} transmit"
      }
     ]
    },
    {
     "title": "Network usage (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{hostname=\"relay-eu\", device=~\"e[t,n][h,s][0-9]+\"}[1m])*8",
       "legendFormat": "{{device}} receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{hostname=\"relay-eu\", device=~\"e[t,n][h,s][0-9]+\"}[1m])*8",
       "legendFormat": "{{device}} transmit"
      }
     ]
    },
    {
     "title": "Network usage (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{hostname=\"relay-ru\", device=~\"e[t,n][h,s][0-9]+\"}[1m])*8",
       "legendFormat": "{{device}} receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{hostname=\"relay-ru\", device=~\"e[t,n][h,s][0-9]+\"}[1m])*8",
       "legendFormat": "{{device}} transmit"
      }
     ]
    },
    {
     "title": "Disk Space Used (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{hostname=\"producer\",device!~'rootfs'} - node_filesystem_avail_bytes{hostname=\"producer\",device!~'rootfs'}) / node_filesystem_size_bytes{hostname=\"producer\",device!~'rootfs'}) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{hostname=\"relay-eu\",device!~'rootfs'} - node_filesystem_avail_bytes{hostname=\"relay-eu\",device!~'rootfs'}) / node_filesystem_size_bytes{hostname=\"relay-eu\",device!~'rootfs'}) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Space Used (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{hostname=\"relay-ru\",device!~'rootfs'} - node_filesystem_avail_bytes{hostname=\"relay-ru\",device!~'rootfs'}) / node_filesystem_size_bytes{hostname=\"relay-ru\",device!~'rootfs'}) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk usage (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{hostname=\"producer\"}[1m])",
       "legendFormat": "{{device}} read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{hostname=\"producer\"}[1m])",
       "legendFormat": "{{device}} write"
      }
     ]
    },
    {
     "title": "Disk usage (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{hostname=\"relay-eu\",device!~\"dm-[0-9]\"}[1m])",
       "legendFormat": "{{device}} read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{hostname=\"relay-eu\",device!~\"dm-[0-9]\"}[1m])",
       "legendFormat": "{{device}} write"
      }
     ]
    },
    {
     "title": "Disk usage (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{hostname=\"relay-ru\",device!~\"dm-[0-9]\"}[1m])",
       "legendFormat": "{{device}} read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{hostname=\"relay-ru\",device!~\"dm-[0-9]\"}[1m])",
       "legendFormat": "{{device}} write"
      }
     ]
    },
    {
     "title": "File Descriptors (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{hostname=\"producer\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "File Descriptors (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{hostname=\"relay-eu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "File Descriptors (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{hostname=\"relay-ru\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cardano Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connected Peers (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_peerSelection_hot{hostname=\"producer\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Connected Peers (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_peerSelection_hot{hostname=\"relay-ru\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Connected Peers (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_peerSelection_hot{hostname=\"relay-eu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Mempool Transactions (producer node)",
     "type": "timeseries",
     "description": "current",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "tx" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_txsInMempool_int{hostname=\"producer\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Mempool Transactions (relay-ru node)",
     "type": "timeseries",
     "description": "current",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "tx" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_txsInMempool_int{hostname=\"relay-ru\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Mempool Transactions (relay-eu node)",
     "type": "timeseries",
     "description": "current",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "tx" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_txsInMempool_int{hostname=\"relay-eu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Mempool bytes (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_mempoolBytes_int{hostname=\"producer\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Mempool bytes (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_mempoolBytes_int{hostname=\"relay-ru\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Mempool bytes (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_mempoolBytes_int{hostname=\"relay-eu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Time Synchronization (producer node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{hostname=\"producer\"}",
       "legendFormat": "Est. error(s)"
      },
      {
       "expr": "node_timex_offset_seconds{hostname=\"producer\"}",
       "legendFormat": "Offset: Node vs. Ref."
      },
      {
       "expr": "node_timex_maxerror_seconds{hostname=\"producer\"}",
       "legendFormat": "Max. Error (s)"
      }
     ]
    },
    {
     "title": "Time Synchronization (relay-ru node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{hostname=\"relay-ru\"}",
       "legendFormat": "Est. error(s)"
      },
      {
       "expr": "node_timex_offset_seconds{hostname=\"relay-ru\"}",
       "legendFormat": "Offset: Node vs. Ref."
      },
      {
       "expr": "node_timex_maxerror_seconds{hostname=\"relay-ru\"}",
       "legendFormat": "Max. Error (s)"
      }
     ]
    },
    {
     "title": "Time Synchronization (relay-eu node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{hostname=\"relay-eu\"}",
       "legendFormat": "Est. error(s)"
      },
      {
       "expr": "node_timex_offset_seconds{hostname=\"relay-eu\"}",
       "legendFormat": "Offset: Node vs. Ref."
      },
      {
       "expr": "node_timex_maxerror_seconds{hostname=\"relay-eu\"}",
       "legendFormat": "Max. Error (s)"
      }
     ]
    },
    {
     "title": "Producer Node current \"residency\" (amount of live data)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_current_bytes_used{hostname=\"producer\"}/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Relay-RU current \"residency\" (amount of live data)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_current_bytes_used{hostname=\"relay-ru\"}/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Relay-EU current \"residency\" (amount of live data)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_current_bytes_used{hostname=\"relay-eu\"}/(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Producer node block sync speed (blocks / min)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (cardano_node_metrics_blockNum_int{hostname=\"producer\"}[150s]) *60",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Relay-RU node block sync speed (blocks / min)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (cardano_node_metrics_blockNum_int{hostname=\"relay-ru\"}[150s]) *60",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Relay-EU node block sync speed (blocks / min)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (cardano_node_metrics_blockNum_int{hostname=\"relay-eu\"}[150s]) *60",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Aggregate Data Transfer (producer node)",
     "type": "timeseries",
     "description": "1 hour rolling window",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{hostname=\"producer\"}[1h])) * 3600",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Aggregate Data Transfer (relay-ru node)",
     "type": "timeseries",
     "description": "1 hour rolling window",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{hostname=\"relay-ru\"}[1h])) * 3600",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Aggregate Data Transfer (relay-eu node)",
     "type": "timeseries",
     "description": "1 hour rolling window",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes_total{hostname=\"relay-eu\"}[1h])) * 3600",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Max \"residency\" (producer  node)",
     "type": "timeseries",
     "description": "Amount of live data, MBytes",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_max_bytes_used{hostname=\"producer\"} /(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Max \"residency\" (relay-ru node)",
     "type": "timeseries",
     "description": "Amount of live data, MBytes",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_max_bytes_used{hostname=\"relay-ru\"} /(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Max \"residency\" (relay-eu node)",
     "type": "timeseries",
     "description": "Amount of live data, MBytes",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_max_bytes_used{hostname=\"relay-eu\"} /(1024*1024)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Chain Density (producer)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_density_real{hostname=\"producer\"} * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Chain Density (relay-ru)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_density_real{hostname=\"relay-ru\"} * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Chain Density (relay-eu)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_density_real{hostname=\"relay-eu\"} * 100",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}