{
 "title": "Lava Provider",
 "tags": [
  "provider",
  "lava"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "geolocation",
    "label": "Geolocation",
    "query": {
     "query": "label_values(lava_provider_protocol_version,geolocation)"
    }
   },
   {
    "name": "moniker",
    "label": "Provider",
    "query": {
     "query": "label_values(lava_provider_protocol_version{geolocation=\"$geolocation\"},moniker)"
    }
   },
   {
    "name": "chain_id",
    "label": "ChainID",
    "query": {
     "query": "label_values(lava_latest_block{spec!=\"lava\", moniker=\"$moniker\"},spec)"
    }
   },
   {
    "name": "cache",
    "label": "Cache",
    "query": {
     "query": "label_values({job=\"rpc_providers\", moniker=\"$moniker\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Provider statistics",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (geolocation,moniker,spec) (lava_provider_total_relays_serviced{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (geolocation,moniker,spec) (lava_provider_total_cu_serviced{})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (geolocation,moniker,spec) (lava_provider_total_cu_paid{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "lava_provider_chain_status{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "General Info: ${moniker} provider",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Current Version",
   "type": "stat",
   "description": "The current lavap version",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lava_provider_update_info{geolocation=\"$geolocation\", moniker=\"$moniker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Version",
   "type": "stat",
   "description": "The last lavap version",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lava_provider_update_info{geolocation=\"$geolocation\", moniker=\"$moniker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Chains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(lava_latest_block{geolocation=\"$geolocation\", moniker=\"$moniker\", spec!=\"lava\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Chains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(lava_provider_chain_status{geolocation=\"$geolocation\", moniker=\"$moniker\", status=\"provider\"})"
    }
   ]
  },
  {
   "title": "Inactive Сhains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(lava_provider_chain_status{geolocation=\"$geolocation\", moniker=\"$moniker\", status=\"unstaked\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frozen Chains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(lava_provider_chain_status{geolocation=\"$geolocation\", moniker=\"$moniker\", status=\"frozen\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_provider_overall_health{moniker=\"$moniker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chain Interfaces Status ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_provider_disabled_chains{geolocation=\"$geolocation\", moniker=\"$moniker\", spec!=\"lava\"}",
     "legendFormat": "{{chainID}} - {{apiInterface}}"
    }
   ]
  },
  {
   "title": "QoS score",
   "type": "bargauge",
   "description": "The latest QoS score from consumers",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (spec) (lava_consumer_QoS{geolocation=\"$geolocation\", moniker=\"$moniker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total of CUs serviced by chains",
   "type": "bargauge",
   "description": "The total number of CUs serviced by the provider over time.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (spec) (lava_provider_total_cu_serviced{geolocation=\"$geolocation\", moniker=\"$moniker\"}))",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Total CU paid",
   "type": "bargauge",
   "description": "The total number of CUs paid to the provider over time.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(lava_provider_total_cu_paid{geolocation=\"$geolocation\", moniker=\"$moniker\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "General Info: ${cache} cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "The total number of requests",
     "type": "timeseries",
     "description": "The total number of requests to the cache server.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "increase(cache_total_hits{hostname=\"$cache\", total_hits=\"total_hits\"}[1m])",
       "legendFormat": "{{total_hits}}"
      },
      {
       "expr": "increase(cache_total_misses{hostname=\"$cache\", total_misses=\"total_misses\"}[1m])",
       "legendFormat": "{{total_misses}}"
      }
     ]
    },
    {
     "title": "Total number of hits by chains",
     "type": "bargauge",
     "description": "The total number of hits the cache server managed to reply.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (chain_id) (cache_api_specifics{hostname=\"${cache}\", result=\"hit\"}))",
       "legendFormat": "{{chain_id}}"
      },
      {
       "expr": "sum (cache_api_specifics{hostname=\"${cache}\", result=\"hit\"})",
       "legendFormat": "[TOTAL]"
      }
     ]
    },
    {
     "title": "Total number of misses by chains",
     "type": "bargauge",
     "description": "The total number of misses the cache server could not reply.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (chain_id) (cache_api_specifics{hostname=\"${cache}\", result=\"miss\"}))",
       "legendFormat": "{{chain_id}}"
      },
      {
       "expr": "sum (cache_api_specifics{hostname=\"${cache}\", result=\"miss\"})",
       "legendFormat": "[TOTAL]"
      }
     ]
    }
   ]
  },
  {
   "title": "${chain_id} chain for ${moniker}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "chain_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Block heights",
     "type": "stat",
     "description": "The latest block measured",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "lava_latest_block{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\"}",
       "legendFormat": "{{spec}}"
      }
     ]
    },
    {
     "title": "Availability",
     "type": "stat",
     "description": "The chain availability score from a consumer",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (spec) (lava_consumer_QoS{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\", qos_metric=\"availability\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "description": "The chain latency score from a consumer.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (spec) (lava_consumer_QoS{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\", qos_metric=\"latency\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync",
     "type": "stat",
     "description": "The chain sync score from a consumer",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (spec) (lava_consumer_QoS{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\", qos_metric=\"sync/freshness\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total of CUs serviced",
     "type": "stat",
     "description": "The total number of CUs serviced by the provider over time.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (lava_provider_total_cu_serviced{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=\"${chain_id}\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total of CUs paid",
     "type": "stat",
     "description": "The total number of CUs paid to the provider over time.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lava_provider_total_cu_paid{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=\"${chain_id}\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "QoS",
     "type": "timeseries",
     "description": "The latest QoS score from consumers",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (qos_metric) (lava_consumer_QoS{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"${chain_id}\"})",
       "legendFormat": "{{qos_metric}}"
      }
     ]
    },
    {
     "title": "Time of the last block update",
     "type": "timeseries",
     "description": "Timestamp of the last block update received from the serviced node.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(lava_provider_last_serviced_block_update_time_seconds{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\"}[1m])",
       "legendFormat": "block_update_time"
      }
     ]
    },
    {
     "title": "Total errors",
     "type": "timeseries",
     "description": "The total number of errors encountered by the provider over time.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "err/m" } },
     "targets": [
      {
       "expr": "increase(lava_provider_total_errored{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"${chain_id}\"}[1m])",
       "legendFormat": "{{apiInterface}}"
      }
     ]
    },
    {
     "title": "The total number of get specific block queries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "increase(lava_provider_fetch_block_success{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\"}[1m])",
       "legendFormat": "fetch_block_success"
      },
      {
       "expr": "increase(lava_provider_fetch_block_fails{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\"}[1m])",
       "legendFormat": "fetch_block_fails"
      }
     ]
    },
    {
     "title": "The total number of get latest block queries",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "increase(lava_provider_fetch_latest_success{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\"}[1m])",
       "legendFormat": "fetch_latest_block_success"
      },
      {
       "expr": "increase(lava_provider_fetch_latest_fails{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"$chain_id\"}[1m])",
       "legendFormat": "fetch_latest_block_fails"
      }
     ]
    },
    {
     "title": "CUs paid",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(lava_provider_total_cu_paid{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"${chain_id}\"}[1m])",
       "legendFormat": "total_cu_paid"
      }
     ]
    },
    {
     "title": "Relays Serviced",
     "type": "timeseries",
     "description": "The total number of relays serviced by the provider over time.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "increase(lava_provider_total_relays_serviced{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"${chain_id}\"}[1m])",
       "legendFormat": "{{apiInterface}}"
      }
     ]
    },
    {
     "title": "CUs Serviced",
     "type": "timeseries",
     "description": "The total number of CUs serviced by the provider over time.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "cu/m" } },
     "targets": [
      {
       "expr": "increase(lava_provider_total_cu_serviced{geolocation=\"$geolocation\", moniker=\"$moniker\", spec=~\"${chain_id}\"}[1m])",
       "legendFormat": "{{apiInterface}}"
      }
     ]
    }
   ]
  }
 ]
}