{
 "title": "Lava Provider K8S",
 "tags": [
  "provider",
  "lava"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(lava_provider_protocol_version,app_lavanet_io_network)"
    }
   },
   {
    "name": "moniker",
    "label": "Provider",
    "query": {
     "query": "label_values(lava_provider_protocol_version{app_lavanet_io_network=\"$network\"},app_lavanet_io_moniker)"
    }
   },
   {
    "name": "chain_id",
    "label": "ChainID",
    "query": {
     "query": "label_values(lava_latest_block{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec!=\"lava\"},spec)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Provider statistics",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (app_lavanet_io_network,app_lavanet_io_moniker,spec) (lava_provider_total_relays_serviced{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (app_lavanet_io_network,app_lavanet_io_moniker,spec) (lava_provider_total_cu_serviced{})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (app_lavanet_io_network,app_lavanet_io_moniker,spec) (lava_provider_total_cu_paid{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chain Status",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "lava_provider_frozen_status{}", "legendFormat": "__auto" },
      { "expr": "lava_provider_jail_status{}", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "General Info: ${moniker} provider",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Current Version",
   "type": "stat",
   "description": "The current lavap version",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_provider_protocol_version{\r\napp_lavanet_io_network=\"$network\",\r\napp_lavanet_io_moniker=\"$moniker\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Version",
   "type": "stat",
   "description": "The last lavap version",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lava_provider_version_info_active{\r\n    app_lavanet_io_network=\"$network\",\r\n    app_lavanet_io_moniker=\"$moniker\"\r\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Chains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (spec) (\r\n  lava_latest_block{\r\n    app_lavanet_io_network=\"$network\",\r\n    app_lavanet_io_moniker=\"$moniker\",\r\n    spec!=\"lava\"\r\n  }\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Chains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(\r\n  count by (spec) (\r\n    lava_latest_block{\r\n      app_lavanet_io_network=\"$network\",\r\n      app_lavanet_io_moniker=\"$moniker\",\r\n      spec != \"lava\"\r\n    }\r\n    unless\r\n    label_replace(\r\n      lava_provider_frozen_status == 1,\r\n      \"spec\", \"$1\", \"chainID\", \"(.*)\"\r\n    )\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Frozen Chains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (chainID) (\r\n  lava_provider_frozen_status{\r\n    app_lavanet_io_network=\"${network}\",\r\n    app_lavanet_io_moniker=\"${moniker}\"\r\n  } == 1\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jailed Сhains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (chainID) (\r\n  lava_provider_jail_status{\r\n    app_lavanet_io_network=\"${network}\",\r\n    app_lavanet_io_moniker=\"${moniker}\"\r\n  } == 1\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_provider_overall_health{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chain Interfaces Status ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_provider_disabled_chains{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec!=\"lava\"}",
     "legendFormat": "{{chainID}} - {{apiInterface}}"
    }
   ]
  },
  {
   "title": "QoS score",
   "type": "bargauge",
   "description": "The latest QoS score from consumers",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (spec) (lava_consumer_QoS{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total of CUs serviced by chains",
   "type": "bargauge",
   "description": "The total number of CUs serviced by the provider over time.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (spec) (lava_provider_total_cu_serviced{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\"}))",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Total CU paid",
   "type": "bargauge",
   "description": "The total number of CUs paid to the provider over time.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (spec) (lava_provider_total_cu_paid{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\"}))",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "${chain_id} chain for ${moniker}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "chain_id"
  },
  {
   "title": "Block heights",
   "type": "stat",
   "description": "The latest block measured",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "description": "The chain availability score from a consumer",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (spec) (lava_consumer_QoS{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\", qos_metric=\"availability\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "The chain latency score from a consumer.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (spec) (lava_consumer_QoS{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\", qos_metric=\"latency\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "stat",
   "description": "The chain sync score from a consumer",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (spec) (lava_consumer_QoS{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\", qos_metric=\"sync/freshness\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total of CUs serviced",
   "type": "stat",
   "description": "The total number of CUs serviced by the provider over time.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (lava_provider_total_cu_serviced{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total of CUs paid",
   "type": "stat",
   "description": "The total number of CUs paid to the provider over time.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (lava_provider_total_cu_paid{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QoS",
   "type": "timeseries",
   "description": "The latest QoS score from consumers",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (qos_metric) (lava_consumer_QoS{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"})",
     "legendFormat": "{{qos_metric}}"
    }
   ]
  },
  {
   "title": "Time of the last block update",
   "type": "timeseries",
   "description": "Timestamp of the last block update received from the serviced node.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lava_provider_last_serviced_block_update_time_seconds{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "timeseries",
   "description": "The total number of errors encountered by the provider over time.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "err/m" } },
   "targets": [
    {
     "expr": "increase(lava_provider_total_errored{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}} :: {{apiInterface}}"
    }
   ]
  },
  {
   "title": "The total number of get specific block queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(lava_provider_fetch_block_success{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}} :: fetch_block_success"
    },
    {
     "expr": "increase(lava_provider_fetch_block_fails{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}} :: fetch_block_fails"
    }
   ]
  },
  {
   "title": "The total number of get latest block queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(lava_provider_fetch_latest_success{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}} :: fetch_latest_block_success"
    },
    {
     "expr": "increase(lava_provider_fetch_latest_fails{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}} :: fetch_latest_block_fails"
    }
   ]
  },
  {
   "title": "CUs paid",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(lava_provider_total_cu_paid{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Relays Serviced",
   "type": "timeseries",
   "description": "The total number of relays serviced by the provider over time.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(lava_provider_total_relays_serviced{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}} :: {{apiInterface}}"
    },
    {
     "expr": "sum(increase(lava_provider_total_relays_serviced{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CUs Serviced",
   "type": "timeseries",
   "description": "The total number of CUs serviced by the provider over time.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cu/m" } },
   "targets": [
    {
     "expr": "increase(lava_provider_total_cu_serviced{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m])",
     "legendFormat": "{{pod}} :: {{apiInterface}}"
    },
    {
     "expr": "sum (increase(lava_provider_total_cu_serviced{app_lavanet_io_network=\"$network\", app_lavanet_io_moniker=\"$moniker\", spec=\"$chain_id\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "The total number of requests",
     "type": "timeseries",
     "description": "The total number of requests to the cache server.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "reqpm" } },
     "targets": [
      {
       "expr": "sum by (service) (increase(cache_total_hits{total_hits=\"total_hits\"}[1m]))",
       "legendFormat": "Total hits"
      },
      {
       "expr": "sum by (service) (increase(cache_total_misses{total_misses=\"total_misses\"}[1m]))",
       "legendFormat": "Total misses"
      }
     ]
    },
    {
     "title": "Total number of hits by chains",
     "type": "bargauge",
     "description": "The total number of hits the cache server managed to reply.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (chain_id) (cache_api_specifics{result=\"hit\"}))",
       "legendFormat": "{{chain_id}}"
      },
      {
       "expr": "sum (cache_api_specifics{result=\"hit\"})",
       "legendFormat": "[TOTAL]"
      }
     ]
    },
    {
     "title": "Total number of misses by chains",
     "type": "bargauge",
     "description": "The total number of misses the cache server could not reply.",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 328 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (chain_id) (cache_api_specifics{result=\"miss\"}))",
       "legendFormat": "{{chain_id}}"
      },
      {
       "expr": "sum (cache_api_specifics{result=\"miss\"})",
       "legendFormat": "[TOTAL]"
      }
     ]
    }
   ]
  }
 ]
}