{
 "title": "Starknet",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gateway_method",
    "label": "Gateway Method",
    "query": {
     "query": "label_values(gateway_requests_total,method)"
    }
   },
   {
    "name": "rpc_method",
    "label": "RPC Method",
    "query": {
     "query": "label_values(rpc_method_calls_total,method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "description": "Pathfinder build info",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pathfinder_build_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Highest block",
   "type": "stat",
   "description": "Height of the blockchain",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "highest_block{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current block",
   "type": "stat",
   "description": "Currently sync'd block height of the node",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_block{}", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Block time",
   "type": "stat",
   "description": "Timestamp difference between the current block and its parent.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_time{}", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Block latency",
   "type": "stat",
   "description": "Delay between current block being published and sync'd locally",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_latency{}", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Block processing",
   "type": "stat",
   "description": "Time taken to process and store the current block",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_processing{}", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Block download",
   "type": "stat",
   "description": "Time taken to download current block's data excluding classes",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_download{}", "legendFormat": "{{method}}" }
   ]
  },
  {
   "title": "Total gateway requests ($gateway_method)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(gateway_requests_total{method=~\"$gateway_method\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum by (method) (rate(gateway_requests_failed_total{method=~\"$gateway_method\"}[$__rate_interval]))",
     "legendFormat": "{{method}} :: failed"
    }
   ]
  },
  {
   "title": "Total RPC method calls ($rpc_method)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_method_calls_total{method=~\"$rpc_method\"}[$__rate_interval])",
     "legendFormat": "{{method}}_{{version}}"
    },
    {
     "expr": "rate(rpc_method_calls_failed_total{method=~\"$rpc_method\"}[$__rate_interval])",
     "legendFormat": "{{method}}_{{version}} :: Failed"
    }
   ]
  },
  {
   "title": "Block time",
   "type": "timeseries",
   "description": "Timestamp difference between the current block and its parent.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "block_time{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block latency",
   "type": "timeseries",
   "description": "Delay between current block being published and sync'd locally",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "block_latency{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "description": "Time taken to process and store the current block.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "block_processing{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block download",
   "type": "timeseries",
   "description": "Time taken to download current block's data, excluding classes.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "block_download{}", "legendFormat": "__auto" }
   ]
  }
 ]
}