{
 "title": "Traefik",
 "description": "Traefik dashboard",
 "tags": [
  "prometheus",
  "traefik"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"proxy\"},hostname)"
    }
   },
   {
    "name": "entrypoint",
    "label": "Entrypoint",
    "query": {
     "query": "label_values({hostname=\"$hostname\", entrypoint!=\"traefik\"},entrypoint)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values({hostname=\"$hostname\", service!~\"api|acme-http|dashboard|noop|prometheus\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Entrypoint  Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{entrypoint!=\"traefik\", entrypoint!=\"metrics\"}) by (hostname,entrypoint)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_entrypoint_requests_total{entrypoint!=\"traefik\", entrypoint!=\"metrics\"}) by (hostname,entrypoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{}) by (hostname, service)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(traefik_service_requests_total{}) by (hostname, service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests by Status code 4xx / 5xx",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (increase(traefik_service_request_duration_seconds_bucket{hostname=\"$hostname\", code!~\"0|[2-3][0-9]{2}\", le=\"+Inf\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "[$hostname] ${entrypoint} entrypoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections{hostname=\"$hostname\", entrypoint=\"$entrypoint\"}) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_entrypoint_requests_total{hostname=\"$hostname\", entrypoint=\"$entrypoint\"}[1m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "Total Requests by Status code",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(rate(traefik_entrypoint_request_duration_seconds_bucket{hostname=\"$hostname\", entrypoint=\"$entrypoint\", code!=\"0\", le=\"+Inf\"}[1m])) by (code)",
       "legendFormat": "{{entrypoint}} [{{code}}]"
      }
     ]
    },
    {
     "title": "Average response time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{hostname=\"$hostname\", entrypoint=\"$entrypoint\", code!=\"0\"}) by (code) / sum(traefik_entrypoint_request_duration_seconds_count{hostname=\"$hostname\", entrypoint=\"$entrypoint\", code!=\"0\"}) by (code)",
       "legendFormat": " {{entrypoint}} [{{code}}]"
      }
     ]
    },
    {
     "title": "Status code 2xx/3xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(traefik_entrypoint_requests_total{hostname=\"$hostname\", entrypoint=\"$entrypoint\", code=~\"[23][0-9][0-9]\"}[1m])",
       "legendFormat": "{{method}} [{{code}}]"
      }
     ]
    },
    {
     "title": "Status code 4xx/5xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(traefik_entrypoint_requests_total{hostname=\"$hostname\", entrypoint=\"$entrypoint\", code=~\"[^23][0-9][0-9]\"}[1m])",
       "legendFormat": "{{method}} [{{code}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "[${hostname}] ${service} service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{hostname=\"$hostname\", service=\"$service\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{hostname=\"$hostname\", service=\"$service\"}[1m])) by (service)",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "Total Requests by Status code",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_request_duration_seconds_bucket{hostname=\"$hostname\", service=\"$service\", code!=\"0\", le=\"+Inf\"}[1m])) by (code)",
     "legendFormat": "{{service}} [{{code}}]"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{hostname=\"$hostname\", service=\"$service\", code!=\"0\"}) by (code) / sum(traefik_service_request_duration_seconds_count{hostname=\"$hostname\", service=\"$service\", code!=\"0\"}) by (code)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (method, service) (rate(traefik_service_requests_bytes_total{hostname=\"$hostname\", service=\"$service\", protocol=\"http\"}[1m]))",
     "legendFormat": "[{{method}}] {{service}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (method, service) (rate(traefik_service_responses_bytes_total{hostname=\"$hostname\", service=~\"$service\", protocol=\"http\"}[1m]))",
     "legendFormat": "[{{method}}] {{service}}"
    }
   ]
  }
 ]
}