---
version: '3.9'
services:
  nibiru-node:
    container_name: nibiru-node
    image: ${IMAGE}
    environment:
    - KEY=<key name>
    - KEY_PASS=<insert password>
    - CHAINID=nibiru-itn-2
    - MONIKER=<moniker name>
    - KEYRING=file
    - KEYALGO=eth_secp256k1
    - LOGLEVEL=info
    - CONFIG_PATH=/root/.nibid
    ports:
    - '26656:26656'
    - '26660:26660'
    volumes:
    - /opt/nibiru:/root/.nibid
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: '14gb'
    restart: unless-stopped
