---
version: '3.9'
services:
  node-testnet:
    image: svetekllc/nibiru:v0.21.11
    env_file:
      - testnet.env
    ports:
      - '26656:26656'
      - '26660:26660'
    volumes:
      - /opt/nvme0n1/nibiru:/root/.nibid
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - nibiru
    restart: unless-stopped

  node-mainnet:
    image: svetekllc/nibiru:v1.0.0
    labels:
      network: mainnet
    env_file:
      - mainnet.env
    ports:
      - '13656:13656'
      - '13660:13660'
    volumes:
      - /opt/nvme1n1/nibiru:/root/.nibid
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '16gb'
    networks:
      - nibiru
    restart: unless-stopped

  pricefeeder-testnet:
    image: pricefeeder
    build: ./pricefeeder
    env_file:
      - pricefeeder.env
    networks:
      - nibiru
    restart: unless-stopped

networks:
  nibiru:
    name: nibiru
