---
version: '3.9'
services:
  cache:
    image: svetekllc/lava:v0.27.1-cache
    env_file:
      - cache.env
    ports:
      - '23101:23101'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - lava
    restart: unless-stopped

  node:
    image: svetekllc/lava:v0.27.0-validator
    env_file:
      - node.env
    ports:
      - '23656:23656'
      - '23660:23660'
    volumes:
      - /opt/testnet/lava:/root/.lava
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '16gb'
    networks:
      - lava
    restart: unless-stopped

  provider:
    image: svetekllc/lava:v0.27.1-provider
    env_file:
      - provider.env
    ports:
      - '23001:23001'
    volumes:
      - /opt/testnet/lava:/root/.lava
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '16gb'
    networks:
      - lava
      - cosmos
      - starknet
    restart: unless-stopped

networks:
  lava:
    name: lava
  cosmos:
    name: cosmos
    external: true
  starknet:
    name: starknet
    external: true
