---
version: '3.9'
services:
  node:
    image: svetekllc/juneo:main-node
    labels:
      network: testnet
    command:
      - '--config-file=/root/.juneogo/config.json'
    ports:
      - '9650:9650'
      - '9651:9651'
    volumes:
      - /opt/nvme0n1/juneo:/root/.juneogo
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - juneo
    restart: unless-stopped

networks:
  juneo:
    name: juneo