---
version: '3.9'
services:
  node:
    image: svetekllc/osmosis:v20.1.0
    env_file:
      - node.env
    ports:
      - '11656:11656'
      - '11660:11660'
    volumes:
      - /opt/nvme1n1/osmosis:/root/.osmosisd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '24gb'
    networks:
      - osmosis
    restart: unless-stopped

networks:
  osmosis:
    name: osmosis