---
version: '3.9'
services:
  node_exporter:
    image: prom/node-exporter:v1.6.1
    labels:
      network: mainnet
    volumes:
      - type: 'bind'
        source: '/'
        target: '/rootfs'
        read_only: true
    command:
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|run|mnt)($$|/)'
    pid: 'host'
    network_mode: host
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    labels:
      network: mainnet
    ports:
    - 18080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring
    restart: unless-stopped

  smartctl:
    image: prometheuscommunity/smartctl-exporter
    labels:
      org.label-schema.group: monitoring
      network: mainnet
    privileged: true
    user: root
    ports:
    - 9633:9633
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    name: monitoring
