---
name: monitoring

services:
  node_exporter:
    image: prom/node-exporter:v1.7.0
    labels:
      network: mainnet
    volumes:
      - type: 'bind'
        source: '/'
        target: '/rootfs'
        read_only: true
      - type: 'bind'
        source: '/opt/node-tools/monitoring/metrics'
        target: '/opt/metrics'
        read_only: true
    command:
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|run|mnt)($$|/)'
      - '--collector.textfile.directory=/opt/metrics'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512M'
    pid: 'host'
    network_mode: host
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    labels:
      network: mainnet
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    privileged: true
    ports:
    - 18080:8080
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512M'
    restart: unless-stopped

  smartctl:
    image: prometheuscommunity/smartctl-exporter
    labels:
      org.label-schema.group: monitoring
      network: mainnet
    privileged: true
    user: root
    ports:
    - 9633:9633
    networks:
      - monitoring
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '512M'
    restart: unless-stopped

networks:
  monitoring:
    name: monitoring
