{
 "title": "Cosmos Staking Monitoring",
 "description": "Stats of a Cosmos validator",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "nodetype", "query": "${VAR_NODETYPE}" },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values({nodetype=\"cosmos\"}, network)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values({network=\"$network\", nodetype=\"$nodetype\"}, hostname)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values({network=\"$network\", hostname=\"$hostname\", nodetype=\"$nodetype\"}, nodename)"
    }
   },
   {
    "name": "moniker",
    "label": "Moniker",
    "query": {
     "query": "label_values({hostname=\"$hostname\", nodename=\"$nodename\", nodetype=\"$nodetype\"}, moniker)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rank",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(cosmos_validator_rank{moniker=\"$moniker\"})",
       "legendFormat": "{{ moniker }}"
      }
     ]
    },
    {
     "title": "Active",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cosmos_validators_active{moniker=\"$moniker\"}"
      }
     ]
    },
    {
     "title": "Jailed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cosmos_validator_jailed{moniker=\"$moniker\"}"
      }
     ]
    },
    {
     "title": "Syncing",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tendermint_consensus_state_syncing{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\",}"
      }
     ]
    },
    {
     "title": "Total delegations",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cosmos_validator_delegations{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}) by (denom)",
       "legendFormat": "{{ denom }}"
      }
     ]
    },
    {
     "title": "Delegations count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cosmos_validator_delegations{moniker=\"$moniker\"})",
       "legendFormat": "{{ moniker }}"
      }
     ]
    },
    {
     "title": "Redelegations count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cosmos_validator_redelegations{moniker=\"$moniker\"}) OR on() vector(0)",
       "legendFormat": "{{ moniker }}"
      }
     ]
    },
    {
     "title": "Unbondings count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(cosmos_validator_unbondings{moniker=\"$moniker\"}) OR on() vector(0)",
       "legendFormat": "{{ moniker }}"
      }
     ]
    },
    {
     "title": "Missed blocks",
     "type": "stat",
     "description": "Number of missed blocks",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tendermint_consensus_validator_missed_blocks{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
      }
     ]
    },
    {
     "title": "Commission rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cosmos_validator_commission_rate{moniker=\"$moniker\"}"
      }
     ]
    },
    {
     "title": "Delegations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(cosmos_validator_delegations{moniker=\"$moniker\"}) by (moniker, denom)",
       "legendFormat": "{{ moniker }}, {{ denom }}"
      }
     ]
    },
    {
     "title": "Redelegations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cosmos_validator_redelegations{moniker=\"$moniker\"}) by (moniker, denom)",
       "legendFormat": "{{ moniker }}, {{ denom }}"
      }
     ]
    },
    {
     "title": "Unbondings",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cosmos_validator_unbondings{moniker=\"$moniker\"}) by (moniker, denom)",
       "legendFormat": "{{ moniker }}, {{ denom }}"
      }
     ]
    },
    {
     "title": "Rewards",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cosmos_validator_rewards{moniker=\"$moniker\"}",
       "legendFormat": "{{ moniker }}, {{ denom }}"
      }
     ]
    },
    {
     "title": "Commission",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "cosmos_validator_commission{moniker=\"$moniker\"}",
       "legendFormat": "{{ moniker }}, {{ denom }}"
      }
     ]
    },
    {
     "title": "Missed blocks",
     "type": "timeseries",
     "description": "Validator missed blocks",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "tendermint_consensus_validator_missed_blocks{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "missed blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "cosmos_validator_missed_blocks{moniker=\"$moniker\"}",
       "legendFormat": "{{ moniker }}"
      }
     ]
    },
    {
     "title": "Delegations",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "cosmos_validator_delegations{moniker=\"$moniker\"}"
      }
     ]
    },
    {
     "title": "Redelegations",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "cosmos_validator_redelegations{name=\"$node_name\"} "
      }
     ]
    },
    {
     "title": "Unbondings",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "cosmos_validator_unbondings{moniker=\"$moniker\"} "
      }
     ]
    }
   ]
  },
  {
   "title": "Validator health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chain health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "description": "Height of the chain",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Total bonded tokens",
   "type": "stat",
   "description": "The total number of bonded tokens in the network",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Offline: bonded tokens",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Validators missing blocks",
   "type": "stat",
   "description": "Number of validators missing blocks",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_missed_blocks{moniker=\"$moniker\"} > 0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Top validators missing blocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, cosmos_validators_missed_blocks{nodename=\"$nodename\"} > 0))"
    }
   ]
  },
  {
   "title": "Online validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators-tendermint_consensus_missing_validators{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "stat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Offline: voting power %",
   "type": "stat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(tendermint_consensus_missing_validators_power{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"} / tendermint_consensus_validators_power{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"})"
    }
   ]
  },
  {
   "title": "Top missed blocks",
   "type": "stat",
   "description": "Number of highest missed blocks for validators on chain",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validators_missed_blocks{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"})"
    }
   ]
  },
  {
   "title": "Offline validators",
   "type": "stat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Confirmed Tx",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\",}"
    }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "stat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "description": "Block size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(increase(tendermint_consensus_height{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}[1m]))"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of block produced last minute",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(tendermint_consensus_height{network=\"$network\", hostname=\"$hostname\", nodename=\"$nodename\"}[1m])"
    }
   ]
  }
 ]
}