{
 "title": "Lava Provider",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Block heights",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{spec!=\"lava\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Total Chains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lava_latest_block{spec!=\"lava\"})"
    }
   ]
  },
  {
   "title": "Chains Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lava_consumer_QoS{qos_metric=\"availability\"} >= 0.7)"
    }
   ]
  },
  {
   "title": "Chains Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lava_consumer_QoS{qos_metric=\"latency\"} >= 0.7)"
    }
   ]
  },
  {
   "title": "Chains Sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lava_consumer_QoS{qos_metric=\"sync/freshness\"} >= 0.7)"
    }
   ]
  },
  {
   "title": "Service Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lava_consumer_QoS{qos_metric=\"availability\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Service Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lava_consumer_QoS{qos_metric=\"latency\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Service Sync",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lava_consumer_QoS{qos_metric=\"sync/freshness\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Provider Relays Serviced",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(lava_provider_total_relays_serviced{}[$__rate_interval])",
     "legendFormat": "{{spec}} : {{apiInterface}}"
    }
   ]
  },
  {
   "title": "Provider CU Serviced",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(lava_provider_total_cu_serviced{}[$__rate_interval])",
     "legendFormat": "{{spec}} : {{apiInterface}}"
    }
   ]
  },
  {
   "title": "Provider total CU paid",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(lava_provider_total_cu_paid{}[$__rate_interval])*60",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Provider total error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(lava_provider_total_errored{}[$__rate_interval])",
     "legendFormat": "{{spec}} : {{apiInterface}}"
    }
   ]
  }
 ]
}