---
version: '3.9'
services:
  node-testnet:
    image: svetekllc/near:1.37.0-rc.3
    labels:
      network: testnet
    env_file:
      - testnet.env
    ports:
      - '25030:3030'
    volumes:
      - /opt/nvme0n1/near:/root/.near
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '24gb'
    networks:
      - near
    restart: unless-stopped

  node-mainnet:
    image: svetekllc/near:1.36.5
    labels:
      network: mainnet
    env_file:
      - mainnet.env
    ports:
      - '15030:3030'
    volumes:
      - /opt/nvme1n1/near:/root/.near
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '24gb'
    networks:
      - near
    restart: unless-stopped

networks:
  near:
    name: near
