---
name: near

services:
  node-testnet:
    image: svetekllc/near:1.38.0-rc.2
    labels:
      network: testnet
    env_file:
      - testnet.env
    volumes:
      - ${T_DATA_PATH}:/root/.near
    ports:
      - '25030:3030'
    networks:
      - near
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '24gb'
    restart: unless-stopped

  node-mainnet:
    image: svetekllc/near:1.38.0
    labels:
      network: mainnet
    env_file:
      - mainnet.env
    volumes:
      - ${M_DATA_PATH}:/root/.near
    ports:
      - '15030:3030'
    networks:
      - near
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: '32gb'
    restart: unless-stopped

networks:
  near:
    name: near
