---
version: '3.9'
services:
  node:
    image: svetekllc/cascadia:v0.2.0-node
    labels:
      network: testnet
    env_file:
      - node.env
    ports:
      - '22656:22656'
      - '22660:22660'
    volumes:
      - /opt/nvme0n1/cascadia:/root/.cascadiad
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - cascadia
    restart: unless-stopped

networks:
  cascadia:
    name: cascadia
