---
version: '3.9'
services:
  node:
    image: svetekllc/evmos:v16.0.3
    labels:
      network: mainnet
    env_file:
      - node.env
    ports:
      - '11090:11090'
      - '11317:11317'
      - '11545:11545'
      - '11656:11656'
      - '11657:11657'
      - '11660:11660'
    volumes:
      - /opt/nvme3n1/evmos:/root/.evmosd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: '32gb'
    networks:
      - evmos
    restart: unless-stopped

networks:
  evmos:
    name: evmos
