---
version: '3.9'
services:
  validator-testnet:
    image: svetekllc/haqq-node:v1.6.1
    labels:
      network: testnet
    env_file:
      - testnet.env
    ports:
      - '36656:36656'
      - '36660:36660'
    volumes:
      - /opt/haqq-testnet:/root/.haqqd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: '14gb'
    restart: unless-stopped

  validator-mainnet:
    image: svetekllc/haqq-node:v1.6.1
    labels:
      network: mainnet
    env_file:
      - mainnet.env
    ports:
    - '26656:26656'
    - '26660:26660'
    volumes:
    - /opt/haqq-mainnet:/root/.haqqd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: '14gb'
    restart: unless-stopped
