---
version: '3.9'
services:
  node-testnet:
    image: svetekllc/haqq-node:v1.6.1
    labels:
      network: testnet
    env_file:
      - testnet.env
    ports:
      - '20656:20656'
      - '20660:20660'
    volumes:
      - /opt/testnet/haqq:/root/.haqqd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: unless-stopped

  node-mainnet:
    image: svetekllc/haqq-node:v1.6.2
    labels:
      network: mainnet
    env_file:
      - mainnet.env
    ports:
    - '10656:10656'
    - '10660:10660'
    volumes:
    - /opt/mainnet/haqq:/root/.haqqd
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: unless-stopped
