---
version: '3.9'
services:
  node:
    image: svetekllc/elys:v0.17.0-node
    labels:
      network: testnet
    env_file:
      - node.env
    ports:
      - '24656:24656'
      - '24660:24660'
    volumes:
      - /opt/nvme0n1/elys:/root/.elys
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - elys
    restart: unless-stopped

networks:
  elys:
    name: elys
