---
version: '3.9'
services:
  node:
    image: mantra:latest
    labels:
      network: testnet
    env_file:
      - node.env
    ports:
      - '21656:21656'
      - '21660:21660'
    volumes:
      - /opt/nvme0n1/mantra:/root/.mantrachain
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '16gb'
    networks:
      - mantra
    restart: unless-stopped

networks:
  mantra:
    name: mantra
