http:
  routers:
    avalanche_impulse_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: avalanche_impulse_impulse_expert
      rule: Host(`avalanche.impulse.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    avalanche_impulse_impulse_expert:
      loadBalancer:
        servers:
          - url: "h2c://lava-provider-1:22001"
        passHostHeader: true

