http:
  routers:
    cosmos-hub_impulse_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: cosmos-hub_impulse_impulse_expert
      rule: Host(`cosmos-hub.impulse.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    cosmos-hub_impulse_impulse_expert:
      loadBalancer:
        servers:
          - url: "h2c://lava-provider-1:22001"
        passHostHeader: true

