http:
  routers:
   cosmoshub_adaimpulse_club:
      entryPoints: 
        - web
        - websecure
      service: cosmoshub_adaimpulse_club
      rule: Host(`cosmoshub.adaimpulse.club`)
      tls:
        certResolver: letsencrypt
  services:
   cosmoshub_adaimpulse_club:
      loadBalancer:
        servers:
          - url: "h2c://lava-provider-1:22001"
        passHostHeader: true

