http:
  routers:
    ethereum_impulse_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: ethereum_impulse_impulse_expert
      rule: Host(`ethereum.impulse.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    ethereum_impulse_impulse_expert:
      loadBalancer:
        servers:
          - url: "h2c://lava-provider-1:22001"
        passHostHeader: true

