http:
  routers:
    ethereum_impulse_impulse_expert:
      rule: Host(`ethereum.impulse.impulse.expert`)
      entryPoints:
        - web
        - websecure
      middlewares: ratelimit_1000
      service: ethereum_impulse_impulse_expert
      tls:
        certResolver: letsencrypt
  middlewares:
    ratelimit_1000:
      rateLimit:
        average: 500
  services:
    ethereum_impulse_impulse_expert:
      loadBalancer:
        servers:
          - url: "h2c://lava-provider-1:22001"
        passHostHeader: true

