http:
  routers:
    m-rpc-01_evmos_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: m-rpc-01_evmos_impulse_expert
      rule: Host(`m-rpc-01.evmos.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    m-rpc-01_evmos_impulse_expert:
      loadBalancer:
        servers:
          - url: "http://evmos-node-1:11657"
        passHostHeader: true
