http:
  routers:
    m-rpc-01_canto_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: m-rpc-01_canto_impulse_expert
      rule: Host(`m-rpc-01.canto.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    m-rpc-01_canto_impulse_expert:
      loadBalancer:
        servers:
          - url: "http://canto-node-1:14657"
        passHostHeader: true
