http:
  routers:
    near_impulse_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: near_impulse_impulse_expert
      rule: Host(`near.impulse.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    near_impulse_impulse_expert:
      loadBalancer:
        servers:
          - url: "h2c://lava-provider-1:22001"
        passHostHeader: true

