http:
  routers:
    optimism_impulse_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: optimism_impulse_impulse_expert
      rule: Host(`optimism.impulse.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    optimism_impulse_impulse_expert:
      loadBalancer:
        servers:
          - url: "h2c://lava-provider-1:22001"
        passHostHeader: true

