http:
  routers:
    t-rpc-01_juneo_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: t-rpc-01_juneo_impulse_expert
      rule: Host(`t-rpc-01.juneo.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    t-rpc-01_juneo_impulse_expert:
      loadBalancer:
        servers:
          - url: "http://juneo-node-1:9650"
        passHostHeader: true
