http:
  routers:
    t-rpc-01_mantra_impulse_expert:
      entryPoints:
        - web
        - websecure
      service: t-rpc-01_mantra_impulse_expert
      rule: Host(`t-rpc-01.mantra.impulse.expert`)
      tls:
        certResolver: letsencrypt
  services:
    t-rpc-01_mantra_impulse_expert:
      loadBalancer:
        servers:
          - url: "http://mantra-node-1:26657"
        passHostHeader: true
