---
version: '3.9'
services:
  proxy:
    image: traefik:v2.11
    labels:
      network: mainnet
    ports:
      - '80:80'
      - '443:443'
      - '28080:8080'
    volumes:
      - ./volumes/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - artela
      - canto
      - evmos
      - haqq
      - lava
      - mantra
      - juneo
      - traefik
    restart: unless-stopped

networks:
    artela:
      name: artela
      external: true
    canto:
      name: canto
      external: true
    evmos:
      name: evmos
      external: true
    haqq:
      name: haqq
      external: true
    lava:
      name: lava
      external: true
    mantra:
      name: mantra
      external: true
    juneo:
      name: juneo
      external: true
    traefik:
      name: traefik