---
version: '3.9'
services:
  proxy:
    image: traefik:v2.10
    labels:
      network: mainnet
    ports:
      - '80:80'
      - '443:443'
      - '28080:8080'
    volumes:
      - ./volumes/traefik:/etc/traefik
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    networks:
      - lava
      - mantra
      - nibiru
      - traefik
    restart: unless-stopped

networks:
    traefik:
      name: traefik
    lava:
      name: lava
      external: true
    mantra:
      name: mantra
      external: true
    nibiru:
      name: nibiru
      external: true
