---
version: '3.9'
services:
  proxy:
    image: traefik:v2.10
    labels:
      network: mainnet
    ports:
      - '80:80'
      - '443:443'
      - '28080:8080'
    volumes:
      - ./volumes/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '4gb'
    networks:
      - canto
      - cascadia
      - haqq
      - lava
      - mantra
      - nibiru
      - traefik
    restart: unless-stopped

networks:
    traefik:
      name: traefik
    canto:
      name: canto
      external: true
    cascadia:
      name: cascadia
      external: true
    haqq:
      name: haqq
      external: true
    lava:
      name: lava
      external: true
    mantra:
      name: mantra
      external: true
    nibiru:
      name: nibiru
      external: true
