---
version: '3.9'
services:
  celestia-node:
    container_name: celestia-node
    image: celestia-node:${TAG}
    environment:
    - KEY=celestia_impulse
    - CHAINID=mamaki
    - MONIKER=CelestiaImpulse
    - KEYRING=test
    - KEYALGO=eth_secp256k1
    - LOGLEVEL=info    
    - CONFIG_PATH=/root/.celestia-app
    ports:
    - '1317:1317'
    - '9090:9090'
    - '26656:26656'
    - '26657:26657'
    volumes:
    - /opt/celestia/data:/root/.celestia-app
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: unless-stopped
