---
version: '3.9'
services:
  validator:
    image: svetekllc/lava:v0.25.2-validator
    env_file:
      - validator.env
    ports:
      - '36656:36656'
      - '36660:36660'
    volumes:
      - /opt/testnet/lava:/root/.lava
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - lava
    restart: unless-stopped

  provider:
    image: svetekllc/lava:v0.25.2-provider
    env_file:
      - provider.env
    ports:
      - '23001:23001'
    volumes:
      - /opt/testnet/lava:/root/.lava
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    networks:
      - lava
      - cosmos
      - osmosis
      - starknet
    restart: unless-stopped

networks:
  lava:
    name: lava
  cosmos:
    name: cosmos
    external: true
  osmosis:
    name: osmosis
    external: true
  starknet:
    name: starknet
    external: true
