---
version: '3.9'
services:
  lava-node:
    container_name: lava-node
    image: ${IMAGE}
    environment:
    - KEY=<key name>
    - KEYRING=test
    - KEYALGO=eth_secp256k1
    - MONIKER=<moniker name>
    - NODETYPE=validator
    - CHAINID=lava-testnet-2
    - CONFIG_PATH=/root/.lava
    - LOGLEVEL=info
    ports:
    - '36656:36656'
    - '36660:36660'
    volumes:
    - /opt/lava:/root/.lava
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: unless-stopped

  lava-provider:
    container_name: lava-provider
    image: ${IMAGE}
    environment:
    - CHAINID=lava-testnet-2
    - CONFIG_PATH=/root/.lava
    - GEOLOCATION=2
    - KEY=<key name>
    - KEYRING=test
    - KEYALGO=eth_secp256k1
    - LOGLEVEL=info
    - MONIKER=<moniker name>
    - NODETYPE=provider
    - PROMETHEUS_PORT=23001
    - TOTAL_CONNECTIONS=100
    ports:
     - '22001:22001'
     - '23001:23001'
    volumes:
    - /opt/lava:/root/.lava
    depends_on:
      - lava-node
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: unless-stopped

