---
version: '3.9'
services:
  validator:
    image: ${VAL_IMAGE}
    environment:
      - CHAINID=${CHAIN_ID}
      - CONFIG_PATH=${CONFIG_PATH}
      - DIFF_HEIGHT=${DIFF_HEIGHT}
      - KEY=${VAL_KEY}
      - KEYRING=${VAL_KEYRING}
      - KEYALGO=${KEYALGO}
      - LAVA_RPC=${LAVA_RPC}
      - LOGLEVEL=${VAL_LOGLEVEL}
      - MONIKER=${VAL_MONIKER}
      - PEERS=${PEERS}
      - SEEDS=${SEEDS}
    ports:
      - '36656:36656'
      - '36660:36660'
    # volumes:
    #   - /opt/lava:/root/.lava
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2gb'
    restart: unless-stopped
    entrypoint: ["tail", "-f", "/dev/null"]

  provider:
    image: ${PROV_IMAGE}
    environment:
      - CHAINID=${CHAIN_ID}
      - CONFIG_PATH=${CONFIG_PATH}
      - GEOLOCATION=${GEOLOCATION}
      - KEY=${PROV_KEY}
      - KEYRING=${PROV_KEYRING}
      - KEYALGO=${KEYALGO}
      - LAVA_RPC=${LAVA_RPC}
      - LOGLEVEL=${PROV_LOGLEVEL}
      - MONIKER=${PROV_MONIKER}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - TOTAL_CONNECTIONS=${TOTAL_CONNECTIONS}
    ports:
      - '22001:22001'
      - '23001:23001'
    volumes:
      - /opt/lava:/root/.lava
    depends_on:
      - validator
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '8gb'
    restart: unless-stopped

