version: "3"
services:
  node:
    image: eqlabs/pathfinder:v0.10.2
    labels:
      network: mainnet
    env_file:
      - node.env
    volumes:
      - /opt/nvme0n1/starknet/data:/usr/share/pathfinder/data
    ports:
      - 19546:19546
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    networks:
      - starknet
    restart: unless-stopped

networks:
  starknet:
    name: starknet
