---
version: '3.9'
services:
  node:
    image: eqlabs/pathfinder:v0.10.6
    labels:
      network: mainnet
    env_file:
      - node.env
    ports:
      - 19546:19546
    volumes:
      - /opt/nvme2n1/starknet/data:/usr/share/pathfinder/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '24gb'
    networks:
      - starknet
    restart: unless-stopped

networks:
  starknet:
    name: starknet
