---
version: '3.9'
services:
  node:
    image: svetekllc/cosmos:v13.0.0
    labels:
      network: mainnet
    env_file:
      - node.env
    ports:
      - '12656:12656'
      - '12660:12660'
    volumes:
      - /opt/testnet/cosmos:/root/.gaia
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '24gb'
    networks:
      - cosmos
    restart: unless-stopped

networks:
  cosmos:
    name: cosmos