---
version: '3.9'
services:
  node:
    image: svetekllc/nibiru:v1.0.3
    labels:
      network: mainnet
    env_file:
      - node.env
    ports:
      - '13656:13656'
      - '13660:13660'
    volumes:
      - /opt/nvme2n1/nibiru:/root/.nibid
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '24gb'
    networks:
      - nibiru
    restart: unless-stopped

  pricefeeder:
    image: pricefeeder
    build: ./pricefeeder
    labels:
      network: mainnet
    env_file:
      - pricefeeder.env
    networks:
      - nibiru
    restart: unless-stopped

networks:
  nibiru:
    name: nibiru
